0:
  Name: Fred
  Description: A simple bird, simple movement and no shooting.
  Health: 1
  TouchDamage: 1
  ShootingBehavior:
    Passive: {}
  MovementBehavior:
    Straight:
      Velocity: { x: -100, y: 0 }
      Acceleration: { x: 0, y: 0 }
  BodyColor: '#FF0000'
  HeadColor: '#FF0000'
