export const DEFAULT_ATTRIBUTE_VALUES = {
    BEE_SPEED: 0.1,
    BEE_MAX_HEALTH: 5,
    BEE_HEALTH_REGEN: 0,
    BEE_FIRE_RATE: 1,
    BEE_DAMAGE: 1,
    BEE_SHOT_COUNT: 1,
    BEE_HONEYCOMB_ATTRACTION: 0,
    BEE_HONEYCOMB_ATTRACTION_DISTANCE: 1,
    BEE_BULLET_SPEED: 0.3,
    BEE_CRIT_CHANCE: 0,
    BEE_CRIT_MULTIPLER: 1.1,
    SAMMY_CHANCE: 1,
};

export const DEFAULT_BIRD_ATTRIBUTES = {
    SPEED: 0.15,
    DAMAGE: 1,
    BULLET_SPEED: 0.45,
    CRIT_CHANCE: 0,
    CRIT_MULTIPLIER: 1,
};