Name: Level 2
StartTime: 0:00:00:00.00
EndTime: 0:00:00:20.00

Birds:

# A 'diamond' formation
- Type: 0
  ReleaseTime: 0:00:00:02.00
  Position: { x: 800, y: 200 }
- Type: 0
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 225 }
- Type: 0
  ReleaseTime: 0:00:00:00.00
  Position: { x: 800, y: 175 }
- Type: 0
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 200 }

# A 'diamond' formation
- Type: 0
  ReleaseTime: 0:00:00:02.00
  Position: { x: 800, y: 400 }
- Type: 0
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 425 }
- Type: 0
  ReleaseTime: 0:00:00:00.00
  Position: { x: 800, y: 375 }
- Type: 0
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 400 }

# A 'diamond' formation
- Type: 0
  ReleaseTime: 0:00:00:02.00
  Position: { x: 800, y: 300 }
- Type: 0
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 325 }
- Type: 0
  ReleaseTime: 0:00:00:00.00
  Position: { x: 800, y: 275 }
- Type: 0
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 300 }

# Introduce new bird type as a vertical wall
- Type: 1
  ReleaseTime: 0:00:00:00.30
  Position: { x: 800, y: 250 }
- Type: 1
  ReleaseTime: 0:00:00:00.00
  Position: { x: 800, y: 300 }
- Type: 1
  ReleaseTime: 0:00:00:00.00
  Position: { x: 800, y: 350 }